package com.progresssoft.utils;

public class Constants {

	public static class DaoConstants {
		public static final String CREATE_TABLE_QUERY = "CREATE TABLE IF NOT EXISTS DEALS_DETAILS ( DEAL_ID INT PRIMARY KEY, FROM_CURRENCY_ISO_CODE VARCHAR(3) NOT NULL, TO_CURRENCY_ISO_CODE VARCHAR(3) NOT NULL, DEAL_TIMESTAMP TIMESTAMP NOT NULL, DEAL_AMOUNT DECIMAL(20, 3) NOT NULL)";
		public static final String INSERT_DEAL_QUERY = "INSERT INTO DEALS_DETAILS (DEAL_ID, FROM_CURRENCY_ISO_CODE, TO_CURRENCY_ISO_CODE, DEAL_TIMESTAMP, DEAL_AMOUNT) VALUES (?, ?, ?, ?, ?)";
		public static final String RETRIEVE_DEALS_QUERY = "SELECT * FROM DEALS_DETAILS";
		public static final String DELETE_DEAL_QUERY = "DELETE FROM DEALS_DETAILS WHERE DEAL_ID=?";

	}

}
